# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19L1Cce5RFy-c_DuAJ4t1I0kZXZL0sxeY
"""

cadena = "aprendizaje"

for n in range(len(cadena)):
    print(f"Índice {n}: {cadena[n]}")

def saludar_usuario(nombre):
    print(f"Hola, {nombre}!")

saludar_usuario("Hade")

def imprimir_mensaje():
    print("¡Estoy aprendiendo funciones en Python!")
imprimir_mensaje()